[biomes.biome_1]
name = "Biome One"
type = "Example ecosystem"

[biomes.biome_1.environment]
water_color = [0.5, 0.6, 0.7]
frame_color = [0.3, 0.4, 0.5]

[biomes.biome_1.species.species_1]
name = "Species One"
type = "Flora"
size = 8
color = [0.2, 0.8, 0.3]
description = "A template flora species that serves as the primary producer in this ecosystem."

[biomes.biome_1.species.species_2]
name = "Species Two"
type = "Fauna"
size = 12
color = [0.7, 0.7, 0.9]
eats = ["species_1"]
description = "A template herbivore that feeds on flora and serves as a primary consumer."

[biomes.biome_1.species.species_3]
name = "Species Three"
type = "Fauna"
size = 18
color = [0.9, 0.4, 0.2]
eats = ["species_2"]
description = "A template predator that hunts herbivores in this biome."

[biomes.biome_2]
name = "Biome Two"
type = "Alternative ecosystem"

[biomes.biome_2.environment]
water_color = [0.8, 0.5, 0.4]
frame_color = [0.2, 0.6, 0.8]

[biomes.biome_2.species.species_4]
name = "Species Four"
type = "Flora"
size = 6
color = [0.4, 0.9, 0.1]
description = "An alternative flora species adapted to different environmental conditions."

[biomes.biome_2.species.species_5]
name = "Species Five"
type = "Fauna"
size = 14
color = [0.9, 0.8, 0.2]
eats = ["species_4"]
description = "A grazer species that feeds on the local flora in this biome."

[biomes.biome_2.species.species_6]
name = "Species Six"
type = "Fauna"
size = 22
color = [0.6, 0.2, 0.7]
eats = ["species_5"]
description = "A large predator that controls the population of grazers."
